# ||  || |__\  ||=\ ||==  ||==_     //==\\  ||=||  ==
# ||  || || || || | ||--  ||        ||__||  ||_||  ||
# \\__// || || ||=/ ||==  ||        ||  ||  ||     ||

max-money: 10000000000000
min-money: 0

currency-symbol: '$'